/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable @next/next/no-img-element */
import LayoutAdmin from "@/components/layout-admin";
import { db } from "@/server/db";
import { Button, Loading, Tooltip } from "@nextui-org/react";
import dayjs from "dayjs";
import { ChevronDownIcon } from "@heroicons/react/20/solid";
import { Menu, Transition } from "@headlessui/react";
import "dayjs/locale/id";
import relativeTime from "dayjs/plugin/relativeTime";
import {
  collection,
  doc,
  getDocs,
  orderBy,
  query,
  updateDoc,
} from "firebase/firestore";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useRef, useState, Fragment } from "react";
import dibuat from "../../../../public/dibuat.svg";
import penulis from "../../../../public/penulis.svg";
import styles from "../../../styles/Home.module.css";
import Tambah from "../../../../public/add.svg";
import Link from "next/link";
export default function LayouUser() {
  const route = useRouter();
  dayjs.locale("id");
  dayjs.extend(relativeTime);
  const snapshot = useRef(null);
  const [isLoading, setIsloading] = useState(true);
  const getDBFromFirestore = async () => {
    const querySnapshot = query(collection(db, "Pasien"));
    const gettt = await getDocs(querySnapshot);
    snapshot.current = gettt.docs;
    setTimeout(() => {
      setIsloading(false);
    }, 1000);
  };

  useEffect(() => {
    getDBFromFirestore();
  }, []);

  if (isLoading) {
    return (
      <div className={styles.main}>
        <Loading color={"currentColor"} />
      </div>
    );
  } else {
    const post = snapshot.current;
    const data = Object.values(post);
    return (
      <LayoutAdmin>
        <Head>
          <title>Pasien - Puskesmas Kambang</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo.jpg" />
        </Head>
        <Link
          href={"/admin/kelola-data-pasien/tambah-pasien"}
          className="flex items-center justify-center py-10"
        >
          <Image height={30} src={Tambah} alt="#" />
          <h1>Tambah Pasien</h1>
        </Link>
        <div className="px-5 overflow-x-auto">
          <table className="min-w-full text-sm bg-white divide-y-2 divide-gray-200">
            <thead className="ltr:text-left rtl:text-right bg-[#014E00] text-white">
              <tr>
                <th className="px-4 py-2 font-medium text-left">No.</th>
                <th className="px-4 py-2 font-medium text-left">NIK</th>
                <th className="px-4 py-2 font-medium text-left">Nama</th>
                <th className="px-4 py-2 font-medium text-left">Umur</th>
                <th className="px-4 py-2 font-medium text-left">
                  Tanggal Lahir
                </th>
                <th className="px-4 py-2 font-medium text-left">Alamat</th>
                <th className="px-4 py-2 font-medium text-left">Keluhan</th>
                <th className="px-4 py-2 font-medium text-left">Nama Dokter</th>
                <th className="px-4 py-2 font-medium text-left">Tanggal</th>
                <th className="px-4 py-2 font-medium text-left"></th>
              </tr>
            </thead>

            <tbody className="divide-y divide-gray-200">
              {data.map((e, i) => {
                const Data = e.data();
                return (
                  <tr
                    key={i}
                    className=" bg-gray-50 hover:bg-[#014E00] hover:text-white rounded-lg hover:rounded-lg"
                  >
                    <td className="px-4 py-2 font-medium">{i + 1}.</td>
                    <td className="px-4 py-2 font-medium">{Data.nik}</td>
                    <td className="px-4 py-2 font-medium">{Data.nama}</td>
                    <td className="px-4 py-2 font-medium">{Data.umur}</td>
                    <td className="px-4 py-2 font-medium">{Data.tgl_lahir}</td>
                    <td className="px-4 py-2">{Data.alamat}</td>
                    <td className="px-4 py-2">{Data.keluhan}</td>
                    <td className="px-4 py-2">{Data.nmdokter}</td>
                    <td className="px-4 py-2">{Data.tanggal}</td>
                    <td className="px-4 py-2 ">
                      <Button
                        onPress={() => {
                          route.push(`/admin/kelola-data-pasien/${e.id}`);
                        }}
                        size={"xs"}
                        className="bg-red-700"
                      >
                        Edit
                      </Button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </LayoutAdmin>
    );
  }
}
