/* eslint-disable @next/next/no-img-element */
/* This example requires Tailwind CSS v2.0+ */
import Image from "next/image";
import Link from "next/link";
import { Toaster } from "react-hot-toast";
import home from "../../../public/home.svg";
import kelolapengaduan from "../../../public/kelolapengaduan.svg";
import protectAdmin from "../../protect/protect-admin";
import Head from "next/head";
import { useRouter } from "next/router";
import CardProfile from "../card-profile";
const LayoutAdmin = ({ children }) => {
  const navigation = [
    {
      name: "Kelola Data Pasien",
      icon: home,
      href: "/admin/kelola-data-pasien",
    },
    {
      name: "Kelola Berita",
      icon: kelolapengaduan,
      href: "/admin/kelola-berita",
    },
    {
      name: "Kelola Jadwal Dokter",
      icon: kelolapengaduan,
      href: "/admin/kelola-jadwal-dokter",
    },
  ];
  const route = useRouter();
  return (
    <>
      <Toaster />
      <Head>
        <title>Admin - BPTD III Sumbar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      {/* Mobile */}
      <div className="md:hidden w-full py-2 m-auto items-center bottom-1 fixed z-[9999] bg-white shadow-xl mx-2">
        <div className="flex justify-between p-5 mx-5 rounded-lg shadow-xl">
          {navigation.map((e, i) => (
            <Link className="flex-col items-center" key={i} href={e.href}>
              <Image src={e.icon} width={30} alt={"#"} />
            </Link>
          ))}
        </div>
      </div>
      {/* Destop */}
      <div className="hidden outline-1 border-x-2 md:flex md:w-64 md:flex-col md:fixed md:inset-y-0">
        <div className="flex flex-col flex-1 min-h-0 shadow-xl">
          <div className="flex flex-col flex-1 pt-5 pb-4 overflow-y-auto ">
            <Link
              href={"/"}
              className="pt-4 pb-8 text-xl font-bold text-center"
            >
              Admin
            </Link>

            <nav className="flex flex-col flex-1 px-2 space-y-1 text-sm ">
              {navigation.map((e, i) => (
                <div key={i} div className="flex gap-2 mx-2">
                  <Image src={e.icon} alt={e.name} />
                  <Link
                    className={
                      route.pathname === e.href
                        ? `bg-[#014E00] text-slate-50 py-1 flex items-center px-2 rounded-lg`
                        : `hover:bg-[#014E00] hover:text-white py-1 flex items-center hover:px-2 rounded-lg`
                    }
                    href={e.href}
                  >
                    {e.name}
                  </Link>
                </div>
              ))}
            </nav>
          </div>
          <CardProfile />
        </div>
      </div>
      <div className="flex flex-col flex-1 pl-0 md:pl-64">
        <div>
          <div>{children}</div>
        </div>
      </div>
    </>
  );
};

export default protectAdmin(LayoutAdmin);
