/* eslint-disable react/jsx-key */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import { AnimationOnScroll } from "react-animation-on-scroll";
import profile from "./../../../public/person.svg";
import Layout from "@/components/layout";
export default function Organisasi() {
  const people = [
    {
      nama: "Ns. YASMARTINIS, S.Kep",
      jabatan: "Kepala Puskesmas",
      email: "#",
      hp: "#",
      imageUrl:
        "https://images.unsplash.com/photo-1574100004472-e536d3b6bacc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    },
    {
      nama: "Ns. Merry El Gusna, S.Kep",
      jabatan: "Kepala Tata Usaha",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "Deri Zarwita, SKM.M.Kes",
      jabatan:
        "Penanggung Jawab UKM Esensial & Keperawatan Kesehatan Masyarakat",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "Yurliza Nengsih, Amd. Keb.",
      jabatan: "Penanggung Jawab UKM Pengembangan",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "dr. Riky Eka Putra",
      jabatan: "Penanggung Jawab UKP, Kefarmasian & Lab.",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "Fitri Armanita, S.Tr.Keb.",
      jabatan:
        "Penanggung Jawab JAringan Pelayanan Puskesmas & Jejaring Puskesmas",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "Etdriyani, AMG",
      jabatan: "Penanggung Jawab Bangunan, Prasarana & Peralatan",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
    {
      nama: "dr. Resta Margaretta",
      jabatan: "Penanggung Jawab Mutu",
      email: "#",
      hp: "#",
      imageUrl: "#",
    },
  ];

  return (
    <Layout>
      <Head>
        <title>Struktur Organasisi - Puskesmas Kambang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.jpg" />
      </Head>

      <ul
        role="list"
        className="grid grid-cols-1 gap-6 px-5 py-5 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 lg:px-20"
      >
        {people.map((person, i) => (
          <div className="animate__animated animate__fadeInUpBig">
            <li
              key={person.nama}
              className="flex flex-col h-full col-span-1 text-center bg-white border divide-y divide-gray-200 rounded-lg shadow-xl"
            >
              <div className="flex flex-col flex-1 p-8 ">
                <Image
                  src={profile}
                  alt={"#"}
                  className="flex-shrink-0 object-cover w-32 h-32 mx-auto rounded-full"
                />
                <h3 className="mt-6 text-sm font-bold text-gray-900">
                  {person.nama}
                </h3>
                <dl className="flex flex-col justify-between flex-grow mt-1">
                  <dt className="sr-only">Title</dt>
                  <dt className="sr-only">Role</dt>
                  <dd className="mt-3">
                    <span className="text-xs font-semibold text-slate-500">
                      {person.jabatan}
                    </span>
                  </dd>
                </dl>
              </div>
            </li>
          </div>
        ))}
      </ul>
    </Layout>
  );
}
